<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '/ZapfDingbats',
    'bold' => $fontDir . '/ZapfDingbats',
    'italic' => $fontDir . '/ZapfDingbats',
    'bold_italic' => $fontDir . '/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/Symbol',
    'bold' => $fontDir . '/Symbol',
    'italic' => $fontDir . '/Symbol',
    'bold_italic' => $fontDir . '/Symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '/DejaVuSans-Bold',
    'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
    'italic' => $fontDir . '/DejaVuSans-Oblique',
    'normal' => $fontDir . '/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '/DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '/DejaVuSansMono-Oblique',
    'normal' => $fontDir . '/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '/DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '/DejaVuSerif-Italic',
    'normal' => $fontDir . '/DejaVuSerif',
  ),
  'glyphicons halflings' => array(
    'normal' => $fontDir . '/glyphicons-halflings-normal_91a063d0f3772b152f606edc0383c99d',
  ),
  'font awesome 5 brands' => array(
    'normal' => $fontDir . '/font-awesome-5-brands-normal_dc89d8f2cac2844dc41bcd049687262f',
  ),
  'font awesome 5 free' => array(
    'normal' => $fontDir . '/font-awesome-5-free-normal_5fdc67ca9b832b376fd094e7e10c8cf9',
    '900' => $fontDir . '/font-awesome-5-free-900_39b5d7b2c1ef6365fb52ad0cddf3c8fb',
  ),
  'nunito' => array(
    '200_italic' => $fontDir . '/nunito-200-italic_c6fe6163fa53ae06c4d278afb09f1d1e',
    '300_italic' => $fontDir . '/nunito-300-italic_5564b019de9ee757b8e74969231a39c6',
    'italic' => $fontDir . '/nunito-italic_7a5e338072de710d78e80a0b7b676e13',
    '600_italic' => $fontDir . '/nunito-600-italic_70540b8497fcdcad67439a1da170a6cd',
    'bold_italic' => $fontDir . '/nunito-bold-italic_f7385ade290a5e83b60b5666bb14efdd',
    '800_italic' => $fontDir . '/nunito-800-italic_18f05207d6823bed1efe267692280109',
    '900_italic' => $fontDir . '/nunito-900-italic_7d0c00015d678bd782d128e933b0098e',
    '200' => $fontDir . '/nunito-200_0e1804460d708a8c8812dd2bb9a9d89f',
    '300' => $fontDir . '/nunito-300_ee9ff98a878d2bcec5ac60166e67ac59',
    'normal' => $fontDir . '/nunito-normal_51264aea5373c13e99081e0e39bbfb0d',
    '600' => $fontDir . '/nunito-600_260a41cb865a0435c462e0b12cc10190',
    'bold' => $fontDir . '/nunito-bold_a3fe31648353394ca5aaeaff65373ead',
    '800' => $fontDir . '/nunito-800_85511e1b9b7db85c1ab58555a3c6922c',
    '900' => $fontDir . '/nunito-900_cc18120a1ee07e8f88043c57178bd0cc',
  ),
) ?>